In [1]:
import torch

##Construct a 5x3 matrix, uninitialized
# *****START CODE
x = torch.empty(5,3)
# *****END CODE
print(x)

tensor([[9.1566e+24, 4.5905e-41, 1.8603e-03],
        [4.5905e-41, 9.1494e+24, 4.5905e-41],
        [1.8596e-03, 4.5905e-41, 2.6836e+29],
        [4.5905e-41, 1.9229e-03, 4.5905e-41],
        [9.1621e+24, 4.5905e-41, 1.8597e-03]])


In [2]:
##Construct a randomly initialized matrix from a normal distribution
# *****START CODE
x = torch.randn(5,3)
# *****END CODE
print(x)

tensor([[-0.1880, -0.4328,  0.7875],
        [ 0.9218,  0.3051,  1.1865],
        [ 1.4428,  0.1907,  0.2999],
        [-0.9635,  0.1364, -0.1556],
        [-0.6658,  0.1534,  0.3202]])


In [3]:
##Construct a matrix filled with zeros and of dtype int64
# *****START CODE
x = torch.zeros(5, 3, dtype=torch.int64)
# *****END CODE
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [4]:
##Construct a tensor directly from data
# *****START CODE
x = torch.tensor([5.5, 3])
# *****END CODE
print(x)

tensor([5.5000, 3.0000])


In [5]:
import torch.nn.functional as F

## N is batch size; D_in is input dimension
## H is hidden dimenion; D_out is output dimension

N, D_in, H, D_out = 64, 1000, 100, 10

## Create random input (x) and output (y) data
# *****START CODE
x = torch.randn(N, D_in)
y = torch.randn(N, D_out)
print('x', x.shape)
print('y', y.shape)
# *****END CODE

x torch.Size([64, 1000])
y torch.Size([64, 10])


In [6]:
##Randomly initialize weights from a normal distribution, skipping bias
##Hint: You need 2 weight tensors; one for the raw input tensor (x) and one for the hidden dimension
# *****START CODE
w1 = torch.randn(D_in, H)
w2 = torch.randn(H, D_out)
print('w1', w1.shape)
print('w2', w2.shape)
# *****END CODE

w1 torch.Size([1000, 100])
w2 torch.Size([100, 10])


In [7]:
learning_rate = 1e-6



In [8]:
h = torch.matmul(x, w1)   # output of the hidden dimension
print('h', h.shape)

h torch.Size([64, 100])


In [10]:
h_relu = F.relu(h)        # output of the ReLU function

In [11]:
y_pred = torch.matmul(h_relu, w2)  # final output of the network
print('y_pred', y_pred.shape)

y_pred torch.Size([64, 10])


In [12]:
loss = ((y_pred - y) ** 2).sum()
print(loss)

tensor(26828420.)


In [12]:
d_loss_ypred = 2.0 * (y_pred - y) #(64,10)
d_ypred_w2 = h_relu #(64,100)
d_loss_w2 = torch.matmul(d_ypred_w2.t(), d_loss_ypred) #(100,10)

In [13]:
d_ypred_hrelu = w2 #(100,10)
d_hrelu_h = 1
d_h_w1 = x #(64,1000)
d_loss_w1 = torch.matmul(d_loss_ypred, d_ypred_hrelu.t()) #(1000,100)
d_loss_w1 = torch.matmul(d_h_w1.t(), d_loss_w1) #

In [14]:
w1 = w1 - learning_rate * d_loss_w1
w2 = w2 - learning_rate * d_loss_w2

In [16]:
learning_rate = 1e-6

##specify the number of epochs
# *****START CODE
epochs = 280
# *****END CODE

for t in range(epochs):
    ## Forward pass: compute predicted y
    ## Hint: make use of torch.matmul()
    ## Use ReLU for the activation function
    # *****START CODE
    h = torch.matmul(x, w1)   # output of the hidden dimension   
    h_relu = F.relu(h)        # output of the ReLU function
    y_pred = torch.matmul(h_relu, w2)  # final output of the network
    # *****END CODE
    ## Compute loss
    loss = ((y_pred - y) ** 2).mean()
    ## Print loss
    print(t, loss)

    ## Backward pass; optimization of weights
    ## Minimize the loss with respect to each weight
    ## Hint: Use the chain rule of differentiation

    ## Compute the gradient of w2 with respect to the loss
    # *****START CODE
    d_loss_ypred = 2.0 * (y_pred - y) 
    d_ypred_w2 = h_relu 
    d_loss_w2 = torch.matmul(d_ypred_w2.t(), d_loss_ypred) 
    # *****END CODE

    ## Compute the gradient of w1 with respect to the loss (consider the derivative of ReLU equal to 1)
    # *****START CODE
    d_ypred_hrelu = w2 
    d_hrelu_h = 1
    d_h_w1 = x 
    d_loss_w1 = torch.matmul(d_loss_ypred, d_ypred_hrelu.t()) 
    d_loss_w1 = torch.matmul(d_h_w1.t(), d_loss_w1) #    
    # *****END CODE
    

    ## Update weights
    # *****START CODE
    w1 = w1 - learning_rate * d_loss_w1
    w2 = w2 -learning_rate * d_loss_w2
    # *****END CODE

0 tensor(0.0006)
1 tensor(0.0006)
2 tensor(0.0006)
3 tensor(0.0006)
4 tensor(0.0005)
5 tensor(0.0005)
6 tensor(0.0005)
7 tensor(0.0005)
8 tensor(0.0005)
9 tensor(0.0004)
10 tensor(0.0004)
11 tensor(0.0004)
12 tensor(0.0004)
13 tensor(0.0004)
14 tensor(0.0004)
15 tensor(0.0004)
16 tensor(0.0003)
17 tensor(0.0003)
18 tensor(0.0003)
19 tensor(0.0003)
20 tensor(0.0003)
21 tensor(0.0003)
22 tensor(0.0003)
23 tensor(0.0003)
24 tensor(0.0002)
25 tensor(0.0002)
26 tensor(0.0002)
27 tensor(0.0002)
28 tensor(0.0002)
29 tensor(0.0002)
30 tensor(0.0002)
31 tensor(0.0002)
32 tensor(0.0002)
33 tensor(0.0002)
34 tensor(0.0002)
35 tensor(0.0002)
36 tensor(0.0002)
37 tensor(0.0002)
38 tensor(0.0001)
39 tensor(0.0001)
40 tensor(0.0001)
41 tensor(0.0001)
42 tensor(0.0001)
43 tensor(0.0001)
44 tensor(0.0001)
45 tensor(0.0001)
46 tensor(0.0001)
47 tensor(0.0001)
48 tensor(9.8458e-05)
49 tensor(9.4722e-05)
50 tensor(9.1162e-05)
51 tensor(8.7758e-05)
52 tensor(8.4433e-05)
53 tensor(8.1235e-05)
54 tensor(7.81