# Deep Learning Course: Lab Exercises

In this lab exercise you will become familiar with the PyTorch library in order to solve deep learning problems. The goals of this assignments are as follows:

- familiarize with PyTorch Tensors

- understand how feedforward backpropagation works in neural networks


# Setup

For this exercise the only thing you need is this notebook.

# Note

Apart from the Questions, there are instruction comments throughout the notebook as well as comments inside the code cells beginning with two hashtags (##). In addition, there are #**START CODE  /  #**END CODE comments indicating the start and end of your code sections. Pay attention not to delete these comments.

# Questions

# Q1 - PyTorch Tensors

a) Get familiar with PyTorch Tensors and construct different types of them.

In [1]:
import torch

##Construct a 5x3 matrix, uninitialized
# *****START CODE
x = torch.empty(5,3)
# *****END CODE
print(x)

tensor([[1.3556e-19, 1.8370e+25, 8.9038e-15],
        [4.4721e+21, 1.5956e+25, 6.4620e-04],
        [6.8608e+22, 1.8174e+31, 1.6930e+22],
        [3.0304e+35, 1.1704e-19, 1.2686e+31],
        [1.9203e+31, 1.7255e+25, 1.2703e+25]])


In [2]:
##Construct a randomly initialized matrix from a normal distribution
# *****START CODE

x = torch.randn(5, 3)
# *****END CODE
print(x)

tensor([[-1.0406,  0.0231, -0.4314],
        [-0.1850, -1.6643,  0.1134],
        [-0.8627,  1.9705,  0.2076],
        [ 0.1355, -1.0027,  0.9708],
        [ 0.0202, -0.2064,  0.8382]])


In [3]:
##Construct a matrix filled with zeros and of dtype int64
# *****START CODE

x = torch.zeros(5, 3, dtype=torch.int64)
# *****END CODE
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [4]:
##Construct a tensor directly from data
# *****START CODE
import random

x = torch.tensor([random.randint(3,10) for i in range(10)])
# *****END CODE
print(x)

tensor([6, 9, 6, 9, 4, 3, 3, 5, 6, 5])


#Q2 Backpropagation from scratch

- Create random input and output PyTorch tensors and train a simple network from scratch.

  Warning: You should NOT use any forward/backward commands from PyTorch             library.

In [12]:
import torch.nn.functional as F

## N is batch size; D_in is input dimension
## H is hidden dimenion; D_out is output dimension

N, D_in, H, D_out = 64, 1000, 100, 10

## Create random input (x) and output (y) data
# *****START CODE
x = torch.empty((N,D_in)).normal_(mean=0, std=1)
y = torch.empty((N,D_out)).normal_(mean=0, std=1)
print('x', x.shape)
print('y', y.shape)
# *****END CODE
    

x torch.Size([64, 1000])
y torch.Size([64, 10])


In [22]:
##Randomly initialize weights from a normal distribution, skipping bias
##Hint: You need 2 weight tensors; one for the raw input tensor (x) and one for the hidden dimension
# *****START CODE
w1 = torch.empty((D_in, H)).normal_(mean=0, std=1)
w2 = torch.empty((H, D_out)).normal_(mean=0, std=1)
# *****END CODE
print('w1', w1.shape)
print('w2', w2.shape)


w1 torch.Size([1000, 100])
w2 torch.Size([100, 10])


In [23]:
##define the learning rate
learning_rate = 1e-6


First, implement the forward pass. Try to compute the predicted y_pred value.

In [24]:
## Calculate the output of the hidden dimension
## Hint: make use of torch.matmul()
# *****START CODE
import torch.nn.functional as F
h = torch.matmul(x, w1)                # output of the hidden dimension 
# *****END CODE  
print('h', h.shape)

h torch.Size([64, 100])


In [25]:
## Pass the output of the hidden dimension to the ReLU activation function
# *****START CODE
h_relu = torch.relu(h)           # output of the ReLU function
# *****END CODE  

In [26]:
## Calculate the final output of the network
# *****START CODE
y_pred = torch.matmul(h_relu, w2)            # final output of the network
# *****END CODE
print('y_pred', y_pred.shape)

y_pred torch.Size([64, 10])


Calculate the loss.

In [27]:
## Compute loss
loss = ((y_pred - y) ** 2).mean()
print(loss)

tensor(51117.1562)


Now, implement the backward pass.
You need to minimize the loss with respect to each weight using the chain rule of differentiation.

In [29]:
## Compute the gradient of w2 with respect to the loss
# *****START CODE
E1 = loss*y_pred
dw1 = torch.matmul(E1, h_relu)

# *****END CODE


RuntimeError: mat1 and mat2 shapes cannot be multiplied (64x10 and 64x100)

In [ ]:
## Compute the gradient of w1 with respect to the loss (consider the derivative of ReLU equal to 1)
# *****START CODE


# *****END CODE

In [ ]:
## Update weights
# *****START CODE


# *****END CODE

Repeat the above process for a number of epochs and notice how the value of the loss changes.

In [ ]:
##specify the number of epochs
# *****START CODE
epochs =
# *****END CODE

for t in range(epochs):
  # *****START CODE




  # *****END CODE


